# Container image that runs your code
FROM alpine:3.10

# Copies your code file from your repository to the filesystem path `/` of the container
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

# Code file to execute when the container starts up
ENTRYPOINT ["/entrypoint.sh"]
